Update README.md
When I tried to run mill, i've got
```scala
build.sc:6: type mismatch;
 found   : Seq[mill.scalalib.Dep]
 required: mill.define.Target[mill.util.Loose.Agg[mill.scalalib.Dep]]
  def ivyDeps = Seq(
                   ^
build.sc:6: `T.command` definitions must have 1 parameter list
  def ivyDeps = Seq(
      ^
Compilation Failed
```
My changing fixes it.

Mill 0.2.7
Scala compiler version 2.12.7